Module 10
StephenSo/DevOps-Course-Starter pull request #16
Opened 2021-11-09 08:51 UTC by StephenSo

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2021-11-16 14:31 UTC, hugh-emerson requested changes
The login process is correct and you made a start on the stretch goal to store users in the database, but you're missing a key feature that the exercise asked for - having two levels of users. 

You are currently letting anyone with a GitHub account to edit your to do list. If you want to manage access without storing users in the DB, find out your ID, and then if that's the current user's id, set their role to "writer", or else "reader". Your index.html shouldn't show create/update/delete buttons to a reader. Your routes in app.py that create/update/delete items should throw an error if the current user is only a reader.

Please resubmit after implementing that, or let us know if you need any extra support.

2021-11-16 14:31 UTC, hugh-emerson commented on README.md
> +The application supports pass thru authentication using Git Hub (https://github.com/) accounts. Click on the 'Git Login' link on the main web page to do this. Without authentication you will only be
You could also document:
- How to register the app with GitHub as that's relevant for developers testing the login process locally or adding new environments
- What env vars you can set - either client id/secret or LOGIN_DISABLED

2021-11-16 14:31 UTC, hugh-emerson commented on tests/tests_e2e/test_sel.py
> +    os.environ['LOGIN_DISABLED'] = "False" # Use to override login requirement.
This is kind of confusing but the behaviour is actually correct...

`bool('False')` is equal to True. Which is actually what we want - we want login to be disabled during the tests. I would suggest you make that clearer by setting it equal to 'True'

2021-11-16 14:31 UTC, hugh-emerson commented on todo_app/app.py
> +        MyUser= user_id
This line isn't doing anything.

2021-11-16 14:31 UTC, hugh-emerson commented on todo_app/app.py
> +def WhichUser(flask_login):
Naming convention in Python is snake_case for functions/variables and PascalCase for classes.

2021-11-16 14:31 UTC, hugh-emerson commented on todo_app/templates/index.html
> +    <p  style="text-align:left;font-size: 20px;"> <a href="/NewItem.html">Add a new Item</a></p>
You are showing this to all users rather than just the ones with permission to add new items.

You should pass the whole user object to the template so you can check user.role.

2021-11-16 14:31 UTC, hugh-emerson commented on todo_app/app.py
> +        self.id = user_id
Looks like you didn't finish switching to using the db_users. You are still using this User definition instead of the one in db_users.py

Which is fine, that was a stretch goal, but it's confusing to have unused code around. Let us know if you want any help switching over.

But what you need to do is:
- Delete this class definition
- In load_user, you should actually fetch the user from the database via a mongo client and finding the one with the correct id
- If a user with that ID doesn't exist in the DB yet, insert one.
- Manually set the "role" for yourself to be "writer"

2021-11-16 14:31 UTC, hugh-emerson commented on todo_app/db_users.py
> +        return user_list
You're returning a list of al users.

I think you mean something like `return users.find_one({'id': user_id})` to find the one with the desired id.

2021-12-07 15:24 UTC, StephenSo commented
I have applied the changes requested. Thanks.

2021-12-13 15:53 UTC, hugh-emerson approved these changes
I would say that you should get it working on Heroku as well, but you're already working on Module 11, so fine just to get it working on Azure.

Looks good, so merge when you're ready 👍

2021-12-14 09:48 UTC, merged