Module 3
StephenSo/DevOps-Course-Starter pull request #7
Opened 2021-05-18 11:10 UTC by StephenSo

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2021-05-25 14:40 UTC, JackMead requested changes
Thanks for making those changes - I've left a few thoughts below but I think it's just worth fixing up the end-to-end tests; we should interact with our page rather than just getting our test setup to do that. I've left some other thoughts below that would also be worth taking a look at - feel free to reach out if you have any further questions.

Also worth noting that you can leave the pull request open rather than closing it and opening a new one; when you make any further changes it will update this PR (as long as it's to the same branch) and we can review it again once you've resubmitted it to Aptem

2021-05-25 14:40 UTC, JackMead commented on README.md
> +pip3 install pytest selenium python-dotenv flask flask_wtf
We shouldn't need to ask the user to manually install any of these dependencies - any of these required should be tracked in our pyproject.toml. Now that you've added those dependencies, users should be able to install these automatically with `poetry install` and then run `poetry run pytest` to run the tests in an environment that has those dependencies available

2021-05-25 14:40 UTC, JackMead commented on tests/Integration_test.py
> +        #json_payload = '{"id":"603b8fd8acd0617a9083538c","checkItemStates":[],"closed":false,"dateLastActivity":"2021-04-05T14:41:54.021Z","desc":"Git","descData":{"emoji":{}},"dueReminder":null,"id
Let's delete any commented out lines

2021-05-25 14:40 UTC, JackMead commented on tests/ViewModel_test.py
> +import pytest
These tests look much more tightly defined now, nice

2021-05-25 14:40 UTC, JackMead commented on tests/tests_e2e/test_sel.py
> +def app_addItem():
Here you're creating the item through your test setup - instead we should be doing that within the test itself and we can then combine the setup steps back into a single fixture

2021-05-25 14:40 UTC, JackMead commented on tests/tests_e2e/test_sel.py
> +    assert driver.find_element_by_partial_link_text(test_item_name)
An example of how we could use selenium in this test might be:

```
    driver.get('http://localhost:5000/NewItem.html')
    elem = driver.find_element_by_id('newItem')
    elem.send_keys(test_item_name)
    submit = driver.find_element_by_xpath("//input[@type='submit']")
    submit.click()
    assert driver.find_element_by_partial_link_text(test_item_name)
```

I suggest having a play with that; can you get a similar setup to work for one of the others below?

2021-05-28 10:59 UTC, StephenSo commented on tests/tests_e2e/test_sel.py
> +def app_addItem():
Took me a moment to get this but I did!

2021-05-28 10:59 UTC, StephenSo commented on tests/tests_e2e/test_sel.py
> +    assert driver.find_element_by_partial_link_text(test_item_name)
All done.
Alex was online today to help me finish of the last few bits.  You two really do know your stuff!

2021-06-03 14:34 UTC, JackMead commented on tests/tests_e2e/test_sel.py
> +def app_addItem():
Yeah, it's a subtle change from a code-writing perspective, but it makes a big difference in how useful our test is!

2021-06-03 14:35 UTC, JackMead approved these changes
Thanks for making those changes - your end-to-end test now looks really solid, happy for you to merge this when you're ready 😄

2021-06-06 08:43 UTC, merged